### ISSUE TITLE
Export dist to SASS so we can easily modify the font filepath

### ISSUE THREAD

**Issue by dritterman** [thecotne/square-file-icons#7]
What you have done is absolutely perfect for my use case except for the fact that I can't modify the font filepath during my build process. Would it be possible for you to also export to SASS?

**Comment by thecotne** [comment]
i have planned to migrate from lodash template to sass since less does not support foreach https://github.com/less/less.js/issues/2601

but end result will be css as is now

i have no problem using this css with less just 

``` less
@import (css) "/bower_components/square-file-icons/dist/css/square-file.min.css"
// font file path is auto corrected
```

are you sure sass does not have similar feature?

@dritterman sorry for late response there was no notifications :/

**Comment by dritterman** [comment]
I haven't been able to find a similar feature but I will keep looking. Thanks for getting back to me and for the great library :)
